# This is a basic workflow to help you get started with Actions

name: do-deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:
jobs:
  clone:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set outputs
      run: echo "SHORT_SHA=`echo ${{github.sha}} | cut -c1-8`" >> $GITHUB_ENV
    - name: Check outputs
      run: echo short is ${SHORT_SHA}
            
    - name: info
      run: echo about to git clone https://github.com/yonatanm/where-is-the-kid.git ${{github.sha}} 

    - uses: kevin-leptons/ssh_action@v1
      with:
        host: "ubuntu@ec2-54-92-183-40.compute-1.amazonaws.com"
        key: ${{ secrets.KEY }}
        command: cd where-is-the-kid ; git pull; echo VERSION=${{github.sha}} > version ; . /home/ubuntu/.nvm/nvm.sh ;  npm run deploy