# This is a basic workflow to help you get started with Actions

name: do-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo about to git clone https://github.com/yonatanm/where-is-the-kid.git ${{github.sha}}

    - name: Setup GitHub SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: "ubuntu@ec2-54-92-183-40.compute-1.amazonaws.com"
        private-key: ${{ secrets.KEY }}
#        private-key-name: github
    - name: Clone GitHub repository
      run: git clone https://github.com/yonatanm/where-is-the-kid.git ${{github.sha}}
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build ${{ github.sha }}
#           echo test, and deploy your project.

#       - name: copy file via ssh password
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key : ${{ secrets.KEY }}
#           source: "src"
#           target: "/tmp"
